### PR TITLE
fix image size

### PR DESCRIPTION
**Pull request by mdrianislam0or1**
Issue Title:  bug in sizes #36 

Resize the image size.

fix36

### CODE REVIEW

**Comment by Israel-Laguan** [comment]
@angelik0828 please check if this size is correct

**Comment by heliomar-pena** [comment]
The image now looks pixelated, could you try to use these others of the best quality instead?:

For example www.github.com/logos

**Comment by mdrianislam0or1** [comment]
Sure

**Comment by angelik0828** [comment]
What resolution are we talking about because apparently it is bigger in a lower resolution than in the largest
image
image

check that please!!

**Comment by mdrianislam0or1** [comment]
f2


f1

**Review by heliomar-pena — APPROVED** [review]
Looks good. @angelik0828 check if the logo is ok without the "GitHub" text or if it's necessary?

**Review by Israel-Laguan — APPROVED** [review]

**Comment by angelik0828** [comment]
@mdrianislam0or1 if the text is needed

**Comment by Israel-Laguan** [comment]
SO should be both of these, right @angelik0828 ?
image

**Comment by angelik0828** [comment]
@mdrianislam0or1 definitely must be both

**Review by angelik0828 — APPROVED** [review]

**Review by e-azocar — APPROVED** [review]

**Comment by e-azocar** [comment]
@mdrianislam0or1 please resolve conflicts to merge

**Review by Israel-Laguan — APPROVED** [review]

**Pull request merged**
